# numpy
## اول پکیج ها رو با دستور pip باید نصب کنیم

In [1]:
import numpy as np

## Lets do some basic stuff

In [2]:
a = np.array(5)

In [3]:
a = np.arange(15)

In [4]:
a = a.reshape(3,5)

In [5]:
a.shape

(3, 5)

In [7]:
a.ndim #number of dimensions

2

In [8]:
a.size

15

In [9]:
a.dtype

dtype('int32')

In [16]:
b = np.arange(20)

In [17]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
b = b.reshape(2 , 5 , 2)

In [24]:
b.shape

(2, 5, 2)

In [25]:
b.ndim

3

In [26]:
b.size

20

In [27]:
b.dtype

dtype('int32')

In [28]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## some operations

In [31]:
a = np.array([20,30,40,50])

In [32]:
b = np.arange(4)

In [33]:
b

array([0, 1, 2, 3])

In [34]:
a

array([20, 30, 40, 50])

In [35]:
a - b

array([20, 29, 38, 47])

In [36]:
a + b 

array([20, 31, 42, 53])

In [38]:
c = a * b 

In [40]:
a

array([20, 30, 40, 50])

In [39]:
c > 50

array([False, False,  True,  True])

In [41]:
np.sin(c)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])